# Generated by Django 4.1.7 on 2023-03-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoapp",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
